---
- name: Detect JVM architecture
  ansible.builtin.set_fact:
    jvm_arch: >-
      {%- if ansible_architecture == 'x86_64' -%}
        amd64
      {%- elif ansible_architecture == 'aarch64' -%}
        arm64
      {%- else -%}
        {{ ansible_architecture }}
      {%- endif -%}

- name: Install OpenJDK {{ java_version }}
  ansible.builtin.apt:
    name: "openjdk-{{ java_version }}-jdk"
    state: present
    update_cache: true

- name: Install OpenJDK Headless {{ java_version }}
  ansible.builtin.apt:
    name: "openjdk-{{ java_version }}-jdk-headless"
    state: present

- name: Set JAVA_HOME environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-{{ java_version }}-openjdk-{{ jvm_arch }}"'
    create: true
    mode: "0644"
    state: present

- name: Export JAVA_HOME for system-wide use
  ansible.builtin.copy:
    content: |
      export JAVA_HOME="/usr/lib/jvm/java-{{ java_version }}-openjdk-{{ jvm_arch }}"
      export PATH="$JAVA_HOME/bin:$PATH"
    dest: /etc/profile.d/java.sh
    owner: root
    group: root
    mode: "0644"

- name: Add JAVA_HOME to PATH
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'PATH="/usr/lib/jvm/java-{{ java_version }}-openjdk-{{ jvm_arch }}/bin:{{ ansible_env.PATH }}"'
    regexp: "^PATH="
    state: present

- name: Set default Java version
  community.general.alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ java_version }}-openjdk-{{ jvm_arch }}/bin/java"

- name: Set default Javac version
  community.general.alternatives:
    name: javac
    path: "/usr/lib/jvm/java-{{ java_version }}-openjdk-{{ jvm_arch }}/bin/javac"

- name: Verify Java installation
  ansible.builtin.command: java -version
  register: java_version_output
  changed_when: false

- name: Display Java version
  ansible.builtin.debug:
    var: java_version_output.stderr_lines
