---
# DSpace version configuration
dspace_version: "9.1"
dspace_source_type: "release"  # Options: "release" or "github"
dspace_github_repo: "https://github.com/DSpace/DSpace.git"
dspace_github_branch: "main"
dspace_release_url: "https://github.com/DSpace/DSpace/archive/refs/tags/dspace-{{ dspace_version }}.zip"

# Installation paths
# Versioned directories (actual installation locations)
dspace_install_dir_versioned: "/opt/dspace-{{ dspace_version }}"
dspace_source_dir_versioned: "/opt/dspace-src-{{ dspace_version }}"

# Symlinks (for compatibility and easy access)
dspace_install_dir: "/opt/dspace"
dspace_source_dir: "/opt/dspace-src"

# Legacy symlink for backward compatibility
dspace_legacy_symlink: "/dspace"

# User configuration
dspace_user: "dspace"
dspace_group: "dspace"

# Frontend user configuration (separate from backend)
frontend_user: "dspaceui"
frontend_group: "dspaceui"

# Database configuration
postgres_version: "16"
postgres_db: "dspace"
postgres_user: "dspace"
postgres_password: "dspace"
postgres_host: "localhost"
postgres_port: 5432

# Java configuration
java_version: "17"

# Maven configuration
maven_version: "3.8.8"

# Ant configuration
ant_version: "1.10.14"

# Solr configuration
solr_version: "9.9.0"
solr_port: 8983
solr_home: "/opt/solr"
solr_user: "solr"
solr_group: "solr"

# Tomcat configuration
tomcat_version: "10.1.33"
tomcat_port: 8080
tomcat_home: "/opt/tomcat"
tomcat_user: "tomcat"
tomcat_group: "tomcat"

# DSpace configuration
dspace_server_url: "http://{{ domain_name }}/server"
dspace_ui_url: "http://{{ domain_name }}/"
dspace_name: "DSpace at My Organization"
dspace_admin_email: "admin@localhost"
dspace_admin_firstname: "Admin"
dspace_admin_lastname: "User"
dspace_admin_password: "admin"

# DSpace Frontend (Angular UI) configuration
dspace_frontend_version: "{{ dspace_version }}"  # Keep in sync with backend version
dspace_frontend_source_type: "release"  # Options: "release" or "github"
dspace_frontend_github_repo: "https://github.com/DSpace/dspace-angular.git"
dspace_frontend_github_branch: "main"
dspace_frontend_release_url: "https://github.com/DSpace/dspace-angular/archive/refs/tags/dspace-{{ dspace_frontend_version }}.zip"

# Frontend installation paths
dspace_frontend_source_dir: "/opt/dspace-angular-src-{{ dspace_frontend_version }}"
dspace_frontend_install_dir: "/opt/dspace-angular"
dspace_frontend_config_dir: "{{ dspace_frontend_source_dir }}/config"

# Node.js configuration
nodejs_version: "20"  # LTS version
nodejs_repo_url: "https://deb.nodesource.com/setup_{{ nodejs_version }}.x"

# PM2 configuration
pm2_user: "{{ frontend_user }}"
pm2_home: "/home/{{ pm2_user }}/.pm2"
pm2_app_name: "dspace-ui"
pm2_instances: 1  # Number of instances (can be 'max' for all CPUs)
pm2_exec_mode: "cluster"  # Options: "fork" or "cluster"
pm2_log_dir: "/var/log/pm2"

# Frontend server configuration
dspace_frontend_host: "127.0.0.1"
dspace_frontend_port: 4000
dspace_frontend_namespace: "/"
dspace_frontend_ssl: false

# Email configuration
mail_server: "localhost"
mail_port: 25
mail_username: ""
mail_password: ""
mail_from_address: "dspace-noreply@localhost"

# Build options
maven_opts: "-Xmx1024M -Xms512M"
ant_opts: "-Xmx1024M -Xms512M"

# System settings
timezone: "UTC"
locale: "pl_PL.UTF-8"

# Nginx configuration
nginx_user: "www-data"
nginx_worker_processes: "auto"
nginx_client_max_body_size: "512M"
nginx_redirect_to_https: false  # Set to true to redirect HTTP to HTTPS (when SSL is enabled)

# SSL/Domain configuration
domain_name: "dspace-server.localnet"  # IMPORTANT: Change to your actual domain
ssl_enabled: false  # Set to true when you have a valid domain
certbot_email: "admin@dspace-server.localnet"  # Your email for Let's Encrypt notifications
certbot_staging: false  # Set to true for testing (avoids rate limits)
certbot_webroot_mode: false  # Set to true to use webroot instead of standalone
certbot_use_systemd_timer: false  # Use systemd timer instead of cron for renewal

# Snakeoil SSL configuration (self-signed certificates for development)
use_snakeoil: true  # Use self-signed certificates when ssl_enabled is false
snakeoil_cert_path: "/etc/ssl/certs/dspace-snakeoil.pem"
snakeoil_key_path: "/etc/ssl/private/dspace-snakeoil.key"
snakeoil_cert_country: "US"
snakeoil_cert_state: "State"
snakeoil_cert_locality: "City"
snakeoil_cert_organization: "DSpace Development"