---
# Build and deploy DSpace Angular frontend

# Install dependencies and build
- name: Install npm dependencies
  npm:
    path: "{{ dspace_frontend_source_dir }}"
    state: present
  become_user: "{{ frontend_user }}"
  environment:
    NODE_OPTIONS: "--max-old-space-size=4096"

- name: Build DSpace Angular for production
  command: npm run build:prod
  args:
    chdir: "{{ dspace_frontend_source_dir }}"
  become_user: "{{ frontend_user }}"
  environment:
    NODE_OPTIONS: "--max-old-space-size=4096"
    NODE_ENV: "production"
  register: build_result
  changed_when: true

# Configure PM2 systemd service
- name: Create PM2 systemd service file
  template:
    src: dspaceui.service.j2
    dest: /etc/systemd/system/dspaceui.service
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start PM2 service
  systemd:
    name: dspaceui
    enabled: yes
    state: started
  become: yes

# Verification
- name: Wait for frontend to be ready
  wait_for:
    port: "{{ dspace_frontend_port }}"
    host: localhost
    delay: 10
    timeout: 60
  register: frontend_ready

- name: Test frontend endpoint
  uri:
    url: "http://localhost:{{ dspace_frontend_port }}/"
    method: GET
    status_code: 200
    timeout: 30
  register: frontend_test
  retries: 3
  delay: 10
  until: frontend_test.status == 200
  ignore_errors: yes

- name: Display frontend status
  debug:
    msg:
      - "DSpace Frontend Status:"
      - "  URL: http://localhost:{{ dspace_frontend_port }}"
      - "  Status: {{ 'Running' if frontend_test.status == 200 else 'Not responding' }}"
      - "  PM2 App Name: {{ pm2_app_name }}"
      - "  Process Manager: PM2"
  when: frontend_test is defined