---
# Install Node.js and PM2 prerequisites for DSpace Frontend

- name: Install Node.js dependencies
  apt:
    name:
      - curl
      - gnupg
      - ca-certificates
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add NodeSource GPG key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: '0644'

- name: Add NodeSource repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main"
    state: present
    filename: nodesource
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install build tools for node-gyp
  apt:
    name:
      - build-essential
      - python3
    state: present

# Install PM2
- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Create PM2 log directory
  file:
    path: "{{ pm2_log_dir }}"
    state: directory
    owner: "{{ pm2_user }}"
    group: "{{ frontend_group }}"
    mode: '0755'