---
# Create frontend user and group

- name: Create frontend group
  ansible.builtin.group:
    name: "{{ frontend_group }}"
    state: present
    system: false

- name: Create frontend user
  ansible.builtin.user:
    name: "{{ frontend_user }}"
    group: "{{ frontend_group }}"
    home: "/home/{{ frontend_user }}"
    shell: /bin/bash
    create_home: true
    state: present
    system: false
    comment: "DSpace Frontend User"

- name: Ensure frontend user home directory has correct permissions
  ansible.builtin.file:
    path: "/home/{{ frontend_user }}"
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ frontend_group }}"
    mode: "0755"
