---
- name: Install DSpace Frontend (Angular UI)
  hosts: dspace_servers
  become: yes

  pre_tasks:
    - name: Check if backend is installed
      block:
        - name: Check DSpace backend API
          uri:
            url: "{{ dspace_server_url }}/api"
            method: GET
            status_code: 200
            timeout: 10
          register: backend_check
          failed_when: false

        - name: Warn if backend not available
          debug:
            msg:
              - "WARNING: DSpace backend API is not responding at {{ dspace_server_url }}/api"
              - "The frontend will be installed but may not function properly without the backend."
              - "Please ensure the backend is installed and running."
          when: backend_check.status != 200

  roles:
    - dspace-frontend
    - nginx

  post_tasks:
    - name: Ensure nginx is reloaded
      systemd:
        name: nginx
        state: reloaded

    - name: Display PM2 process status
      command: pm2 list
      become_user: "{{ dspace_user }}"
      register: pm2_status
      changed_when: false

    - name: Show PM2 status
      debug:
        var: pm2_status.stdout_lines

    - name: Test frontend availability
      uri:
        url: "http://localhost:{{ dspace_frontend_port }}/"
        method: GET
        status_code: 200
        timeout: 30
      register: frontend_test
      retries: 3
      delay: 10
      until: frontend_test.status == 200
      ignore_errors: yes

    - name: Test nginx proxy to frontend
      uri:
        url: "http://{{ domain_name }}/"
        method: GET
        status_code: 200
        timeout: 30
        follow_redirects: all
      register: nginx_test
      ignore_errors: yes
      when: domain_name != "dspace.example.com"

    - name: Display installation complete message
      debug:
        msg:
          - "================================================"
          - " DSpace Frontend Installation Complete!"
          - "================================================"
          - ""
          - "Frontend Access URLs:"
          - "  Direct: http://localhost:{{ dspace_frontend_port }}"
          - "  Via Nginx: https://{{ domain_name }}/ (or http:// if SSL not enabled)"
          - ""
          - "Backend API Access:"
          - "  REST API: {{ dspace_server_url }}/api"
          - "  Via Nginx: https://{{ domain_name }}/server/api"
          - ""
          - "PM2 Process Management:"
          - "  Status: sudo -u {{ dspace_user }} pm2 status"
          - "  Logs: sudo -u {{ dspace_user }} pm2 logs {{ pm2_app_name }}"
          - "  Restart: sudo -u {{ dspace_user }} pm2 restart {{ pm2_app_name }}"
          - "  Stop: sudo -u {{ dspace_user }} pm2 stop {{ pm2_app_name }}"
          - ""
          - "Frontend Configuration:"
          - "  Config: {{ dspace_frontend_config_dir }}/config.prod.yml"
          - "  Source: {{ dspace_frontend_source_dir }}"
          - "  Symlink: {{ dspace_frontend_install_dir }}"
          - ""
          - "Service Status:"
          - "  Frontend: {{ 'Running' if frontend_test.status == 200 else 'Not responding (check PM2 logs)' }}"
          - "  Nginx Proxy: {{ 'Working' if nginx_test.status == 200 else 'Not tested or not working' if nginx_test is defined else 'Not tested (using default domain)' }}"
          - ""
          - "Next Steps:"
          - "  1. Update your DNS to point to this server"
          - "  2. Configure SSL certificates if not already done"
          - "  3. Customize the frontend configuration as needed"
          - "  4. Monitor logs for any issues"
          - "================================================"