---
- name: Install Firefox from Mozilla APT Repository
  hosts: dspace_servers
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - firefox

  post_tasks:
    - name: Verify Firefox installation
      command: firefox --version
      register: firefox_check
      changed_when: false
      failed_when: false

    - name: Display installation summary
      debug:
        msg:
          - "Firefox installation completed!"
          - "Firefox version: {{ firefox_check.stdout if firefox_check.rc == 0 else 'Not installed or not in PATH' }}"