---
- name: Import DSpace base setup
  ansible.builtin.import_role:
    name: dspace-base
  tags:
    - dspace_base
    - always

- name: Import DSpace download
  ansible.builtin.import_role:
    name: dspace-download
  tags:
    - dspace_download

- name: Import DSpace build
  ansible.builtin.import_role:
    name: dspace-build
  tags:
    - dspace_build

- name: Import DSpace installation
  ansible.builtin.import_role:
    name: dspace-install
  tags:
    - dspace_install
